<?php
/**
 * CLI script to create a quiz and populate it with questions from a category.
 */

define('CLI_SCRIPT', true);

require(__DIR__ . '/../../config.php');
require_once($CFG->libdir . '/clilib.php');
require_once($CFG->dirroot . '/course/modlib.php');
require_once($CFG->dirroot . '/mod/quiz/lib.php');
require_once($CFG->dirroot . '/mod/quiz/locallib.php');

list($options, $unrecognized) = cli_get_params([
    'courseid' => false,
    'name' => false,
    'categoryid' => false,
    'help' => false,
], [
    'h' => 'help'
]);

if ($options['help'] || !$options['courseid'] || !$options['name'] || !$options['categoryid']) {
    echo "Create a Moodle quiz and populate it with questions from a category.

Options:
--courseid=INT    The ID of the course to create the quiz in.
--name=STRING      The name of the new quiz.
--categoryid=INT  The ID of the question category to pull questions from.
-h, --help        Print out this help.

Example:
php admin/cli/create_quiz.php --courseid=2 --name=\"Final Exam\" --categoryid=5
";
    exit;
}

$courseid = $options['courseid'];
$quizname = $options['name'];
$categoryid = $options['categoryid'];

$course = $DB->get_record('course', ['id' => $courseid], '*', MUST_EXIST);
$category = $DB->get_record('question_categories', ['id' => $categoryid], '*', MUST_EXIST);

// Switch to admin user.
\core\session\manager::set_user(get_admin());

echo "Creating quiz '$quizname' in course: " . format_string($course->fullname) . "\n";

// 1. Prepare module info.
$module = $DB->get_record('modules', ['name' => 'quiz'], '*', MUST_EXIST);
$section = 1; // Default to first section.

$moduleinfo = new stdClass();
$moduleinfo->modulename = 'quiz';
$moduleinfo->module = $module->id;
$moduleinfo->name = $quizname;
$moduleinfo->intro = 'Generated by CLI script.';
$moduleinfo->introformat = FORMAT_HTML;
$moduleinfo->course = $course->id;
$moduleinfo->section = $section;
$moduleinfo->visible = 1;

// Quiz specific defaults (matching mod_quiz_mod_form defaults loosely).
$moduleinfo->attempts = 0; // Unlimited.
$moduleinfo->grademethod = QUIZ_GRADEHIGHEST;
$moduleinfo->decimalpoints = 2;
$moduleinfo->questiondecimalpoints = -1;
$moduleinfo->preferredbehaviour = 'deferredfeedback';
$moduleinfo->shuffleanswers = 1;
$moduleinfo->questionsperpage = 1;

// Required for add_moduleinfo.
$moduleinfo->coursemodule = 0;
$moduleinfo->instance = 0;

// 2. Add the module.
$result = add_moduleinfo($moduleinfo, $course);

if (!$result || !isset($result->instance)) {
    cli_error("Failed to create quiz instance.");
}

$quizid = $result->instance;
$quiz = $DB->get_record('quiz', ['id' => $quizid], '*', MUST_EXIST);

echo "Created quiz ID: $quizid\n";

// 3. Add questions from the category.
$questions = $DB->get_records('question', ['category' => $categoryid, 'parent' => 0, 'hidden' => 0]);

if (empty($questions)) {
    echo "No questions found in category $categoryid. Quiz remains empty.\n";
} else {
    echo "Adding " . count($questions) . " questions to the quiz...\n";
    foreach ($questions as $question) {
        if ($question->qtype === 'random') {
            continue;
        }
        quiz_add_quiz_question($question->id, $quiz);
        echo "  - Added question: " . format_string($question->name) . "\n";
    }
}

echo "Successfully created and populated quiz!\n";
